key_size: 256
public_key: "private.pem" # file to store public key
private_key: "public.pem" # file to store private key
aes_key: "aes_keys_chain.bin" # the AES key is encrypted using the private key
directories:
  - testing_env/Documents
  - testing_env/Downloads
  - testing_env/Pictures
files:
  - exe
  - docx
  - pdf
  - xlsx
